/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AuxiVestingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "beneficiarySchedules"
      | "changeBeneficiary"
      | "contractBalance"
      | "getScheduleIds"
      | "getSchedulesCount"
      | "getVestingInfo"
      | "isFunded"
      | "owner"
      | "releasableAmount"
      | "release"
      | "releaseAll"
      | "renounceOwnership"
      | "revoke"
      | "schedules"
      | "token"
      | "totalCommitted"
      | "totalRequiredTokens"
      | "transferOwnership"
      | "vestedAmount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BeneficiaryChanged"
      | "OwnershipTransferred"
      | "ScheduleCreated"
      | "ScheduleRevoked"
      | "TokensReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "beneficiarySchedules",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeBeneficiary",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getScheduleIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSchedulesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isFunded", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releasableAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseAll",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "schedules",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalCommitted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRequiredTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestedAmount",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "beneficiarySchedules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScheduleIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSchedulesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isFunded", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releasableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "releaseAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "schedules", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalCommitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRequiredTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestedAmount",
    data: BytesLike
  ): Result;
}

export namespace BeneficiaryChangedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    oldBeneficiary: AddressLike,
    newBeneficiary: AddressLike
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    oldBeneficiary: string,
    newBeneficiary: string
  ];
  export interface OutputObject {
    scheduleId: bigint;
    oldBeneficiary: string;
    newBeneficiary: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleCreatedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    beneficiary: AddressLike,
    totalAmount: BigNumberish,
    start: BigNumberish,
    cliff: BigNumberish,
    end: BigNumberish,
    revocable: boolean
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    beneficiary: string,
    totalAmount: bigint,
    start: bigint,
    cliff: bigint,
    end: bigint,
    revocable: boolean
  ];
  export interface OutputObject {
    scheduleId: bigint;
    beneficiary: string;
    totalAmount: bigint;
    start: bigint;
    cliff: bigint;
    end: bigint;
    revocable: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleRevokedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    beneficiary: AddressLike,
    remainingAmount: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    beneficiary: string,
    remainingAmount: bigint
  ];
  export interface OutputObject {
    scheduleId: bigint;
    beneficiary: string;
    remainingAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensReleasedEvent {
  export type InputTuple = [
    scheduleId: BigNumberish,
    beneficiary: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    scheduleId: bigint,
    beneficiary: string,
    amount: bigint
  ];
  export interface OutputObject {
    scheduleId: bigint;
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuxiVesting extends BaseContract {
  connect(runner?: ContractRunner | null): AuxiVesting;
  waitForDeployment(): Promise<this>;

  interface: AuxiVestingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beneficiarySchedules: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  changeBeneficiary: TypedContractMethod<
    [scheduleId: BigNumberish, newBeneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  contractBalance: TypedContractMethod<[], [bigint], "view">;

  getScheduleIds: TypedContractMethod<
    [beneficiary: AddressLike],
    [bigint[]],
    "view"
  >;

  getSchedulesCount: TypedContractMethod<[], [bigint], "view">;

  getVestingInfo: TypedContractMethod<
    [scheduleId: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        beneficiary: string;
        total: bigint;
        vested: bigint;
        released: bigint;
        releasable: bigint;
        start: bigint;
        cliff: bigint;
        end: bigint;
        revocable: boolean;
        revoked: boolean;
      }
    ],
    "view"
  >;

  isFunded: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  releasableAmount: TypedContractMethod<
    [scheduleId: BigNumberish],
    [bigint],
    "view"
  >;

  release: TypedContractMethod<
    [scheduleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseAll: TypedContractMethod<
    [beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revoke: TypedContractMethod<[scheduleId: BigNumberish], [void], "nonpayable">;

  schedules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        beneficiary: string;
        totalAmount: bigint;
        releasedAmount: bigint;
        start: bigint;
        cliff: bigint;
        end: bigint;
        revocable: boolean;
        revoked: boolean;
      }
    ],
    "view"
  >;

  token: TypedContractMethod<[], [string], "view">;

  totalCommitted: TypedContractMethod<[], [bigint], "view">;

  totalRequiredTokens: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vestedAmount: TypedContractMethod<
    [scheduleId: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beneficiarySchedules"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "changeBeneficiary"
  ): TypedContractMethod<
    [scheduleId: BigNumberish, newBeneficiary: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getScheduleIds"
  ): TypedContractMethod<[beneficiary: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSchedulesCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVestingInfo"
  ): TypedContractMethod<
    [scheduleId: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        beneficiary: string;
        total: bigint;
        vested: bigint;
        released: bigint;
        releasable: bigint;
        start: bigint;
        cliff: bigint;
        end: bigint;
        revocable: boolean;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFunded"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releasableAmount"
  ): TypedContractMethod<[scheduleId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[scheduleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseAll"
  ): TypedContractMethod<[beneficiary: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<[scheduleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "schedules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        beneficiary: string;
        totalAmount: bigint;
        releasedAmount: bigint;
        start: bigint;
        cliff: bigint;
        end: bigint;
        revocable: boolean;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalCommitted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRequiredTokens"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vestedAmount"
  ): TypedContractMethod<[scheduleId: BigNumberish], [bigint], "view">;

  getEvent(
    key: "BeneficiaryChanged"
  ): TypedContractEvent<
    BeneficiaryChangedEvent.InputTuple,
    BeneficiaryChangedEvent.OutputTuple,
    BeneficiaryChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleCreated"
  ): TypedContractEvent<
    ScheduleCreatedEvent.InputTuple,
    ScheduleCreatedEvent.OutputTuple,
    ScheduleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleRevoked"
  ): TypedContractEvent<
    ScheduleRevokedEvent.InputTuple,
    ScheduleRevokedEvent.OutputTuple,
    ScheduleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TokensReleased"
  ): TypedContractEvent<
    TokensReleasedEvent.InputTuple,
    TokensReleasedEvent.OutputTuple,
    TokensReleasedEvent.OutputObject
  >;

  filters: {
    "BeneficiaryChanged(uint256,address,address)": TypedContractEvent<
      BeneficiaryChangedEvent.InputTuple,
      BeneficiaryChangedEvent.OutputTuple,
      BeneficiaryChangedEvent.OutputObject
    >;
    BeneficiaryChanged: TypedContractEvent<
      BeneficiaryChangedEvent.InputTuple,
      BeneficiaryChangedEvent.OutputTuple,
      BeneficiaryChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ScheduleCreated(uint256,address,uint256,uint64,uint64,uint64,bool)": TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;
    ScheduleCreated: TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;

    "ScheduleRevoked(uint256,address,uint256)": TypedContractEvent<
      ScheduleRevokedEvent.InputTuple,
      ScheduleRevokedEvent.OutputTuple,
      ScheduleRevokedEvent.OutputObject
    >;
    ScheduleRevoked: TypedContractEvent<
      ScheduleRevokedEvent.InputTuple,
      ScheduleRevokedEvent.OutputTuple,
      ScheduleRevokedEvent.OutputObject
    >;

    "TokensReleased(uint256,address,uint256)": TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;
    TokensReleased: TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;
  };
}
