/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AuxidienOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "ORACLE_ROLE"
      | "getMetalPrices"
      | "getPriceData"
      | "getPricePerOzE6"
      | "getRoleAdmin"
      | "grantOracleRole"
      | "grantRole"
      | "hasRole"
      | "isStale"
      | "lastMetalPrices"
      | "lastUpdateAt"
      | "maxPriceChangeRate"
      | "minUpdateInterval"
      | "renounceRole"
      | "revokeOracleRole"
      | "revokeRole"
      | "setMaxPriceChangeRate"
      | "setMinUpdateInterval"
      | "setPricePerOzE6"
      | "setPriceWithMetals"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MaxPriceChangeRateChanged"
      | "MetalPricesRecorded"
      | "MinUpdateIntervalChanged"
      | "PriceUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMetalPrices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPricePerOzE6",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantOracleRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isStale",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastMetalPrices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastUpdateAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxPriceChangeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minUpdateInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeOracleRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxPriceChangeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinUpdateInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPricePerOzE6",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceWithMetals",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMetalPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPricePerOzE6",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantOracleRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isStale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastMetalPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastUpdateAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPriceChangeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minUpdateInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeOracleRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxPriceChangeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinUpdateInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPricePerOzE6",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceWithMetals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace MaxPriceChangeRateChangedEvent {
  export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
  export type OutputTuple = [oldRate: bigint, newRate: bigint];
  export interface OutputObject {
    oldRate: bigint;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetalPricesRecordedEvent {
  export type InputTuple = [
    goldPrice: BigNumberish,
    silverPrice: BigNumberish,
    platinumPrice: BigNumberish,
    palladiumPrice: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    goldPrice: bigint,
    silverPrice: bigint,
    platinumPrice: bigint,
    palladiumPrice: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    goldPrice: bigint;
    silverPrice: bigint;
    platinumPrice: bigint;
    palladiumPrice: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinUpdateIntervalChangedEvent {
  export type InputTuple = [
    oldInterval: BigNumberish,
    newInterval: BigNumberish
  ];
  export type OutputTuple = [oldInterval: bigint, newInterval: bigint];
  export interface OutputObject {
    oldInterval: bigint;
    newInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    pricePerOzE6: BigNumberish,
    timestamp: BigNumberish,
    updater: AddressLike
  ];
  export type OutputTuple = [
    pricePerOzE6: bigint,
    timestamp: bigint,
    updater: string
  ];
  export interface OutputObject {
    pricePerOzE6: bigint;
    timestamp: bigint;
    updater: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuxidienOracle extends BaseContract {
  connect(runner?: ContractRunner | null): AuxidienOracle;
  waitForDeployment(): Promise<this>;

  interface: AuxidienOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  getMetalPrices: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        gold: bigint;
        silver: bigint;
        platinum: bigint;
        palladium: bigint;
      }
    ],
    "view"
  >;

  getPriceData: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        updatedAt: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;

  getPricePerOzE6: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantOracleRole: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isStale: TypedContractMethod<[maxAge: BigNumberish], [boolean], "view">;

  lastMetalPrices: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        goldPrice: bigint;
        silverPrice: bigint;
        platinumPrice: bigint;
        palladiumPrice: bigint;
      }
    ],
    "view"
  >;

  lastUpdateAt: TypedContractMethod<[], [bigint], "view">;

  maxPriceChangeRate: TypedContractMethod<[], [bigint], "view">;

  minUpdateInterval: TypedContractMethod<[], [bigint], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeOracleRole: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setMaxPriceChangeRate: TypedContractMethod<
    [rate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinUpdateInterval: TypedContractMethod<
    [interval: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPricePerOzE6: TypedContractMethod<
    [newPricePerOzE6: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPriceWithMetals: TypedContractMethod<
    [
      newPricePerOzE6: BigNumberish,
      goldPrice: BigNumberish,
      silverPrice: BigNumberish,
      platinumPrice: BigNumberish,
      palladiumPrice: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMetalPrices"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        gold: bigint;
        silver: bigint;
        platinum: bigint;
        palladium: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPriceData"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        updatedAt: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPricePerOzE6"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantOracleRole"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isStale"
  ): TypedContractMethod<[maxAge: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastMetalPrices"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        goldPrice: bigint;
        silverPrice: bigint;
        platinumPrice: bigint;
        palladiumPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastUpdateAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxPriceChangeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minUpdateInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeOracleRole"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxPriceChangeRate"
  ): TypedContractMethod<[rate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinUpdateInterval"
  ): TypedContractMethod<[interval: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPricePerOzE6"
  ): TypedContractMethod<[newPricePerOzE6: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceWithMetals"
  ): TypedContractMethod<
    [
      newPricePerOzE6: BigNumberish,
      goldPrice: BigNumberish,
      silverPrice: BigNumberish,
      platinumPrice: BigNumberish,
      palladiumPrice: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "MaxPriceChangeRateChanged"
  ): TypedContractEvent<
    MaxPriceChangeRateChangedEvent.InputTuple,
    MaxPriceChangeRateChangedEvent.OutputTuple,
    MaxPriceChangeRateChangedEvent.OutputObject
  >;
  getEvent(
    key: "MetalPricesRecorded"
  ): TypedContractEvent<
    MetalPricesRecordedEvent.InputTuple,
    MetalPricesRecordedEvent.OutputTuple,
    MetalPricesRecordedEvent.OutputObject
  >;
  getEvent(
    key: "MinUpdateIntervalChanged"
  ): TypedContractEvent<
    MinUpdateIntervalChangedEvent.InputTuple,
    MinUpdateIntervalChangedEvent.OutputTuple,
    MinUpdateIntervalChangedEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "MaxPriceChangeRateChanged(uint256,uint256)": TypedContractEvent<
      MaxPriceChangeRateChangedEvent.InputTuple,
      MaxPriceChangeRateChangedEvent.OutputTuple,
      MaxPriceChangeRateChangedEvent.OutputObject
    >;
    MaxPriceChangeRateChanged: TypedContractEvent<
      MaxPriceChangeRateChangedEvent.InputTuple,
      MaxPriceChangeRateChangedEvent.OutputTuple,
      MaxPriceChangeRateChangedEvent.OutputObject
    >;

    "MetalPricesRecorded(uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      MetalPricesRecordedEvent.InputTuple,
      MetalPricesRecordedEvent.OutputTuple,
      MetalPricesRecordedEvent.OutputObject
    >;
    MetalPricesRecorded: TypedContractEvent<
      MetalPricesRecordedEvent.InputTuple,
      MetalPricesRecordedEvent.OutputTuple,
      MetalPricesRecordedEvent.OutputObject
    >;

    "MinUpdateIntervalChanged(uint256,uint256)": TypedContractEvent<
      MinUpdateIntervalChangedEvent.InputTuple,
      MinUpdateIntervalChangedEvent.OutputTuple,
      MinUpdateIntervalChangedEvent.OutputObject
    >;
    MinUpdateIntervalChanged: TypedContractEvent<
      MinUpdateIntervalChangedEvent.InputTuple,
      MinUpdateIntervalChangedEvent.OutputTuple,
      MinUpdateIntervalChangedEvent.OutputObject
    >;

    "PriceUpdated(uint256,uint256,address)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
